### ISSUE TITLE
zmiana typu wartości na energia

### ISSUE THREAD

**Issue by Melgan** [tcich/ha-addon-energa-meter#17]
Hej,
Chciałbym zintegrować Energę bardziej z HA, natomiast wymagane device_class to energy
wg faq HA trzeba zgłosić się do autora
https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities

**Comment by paki111** [comment]
Samodzielnie można sobie dodać `device_class` przez "customizecje"
https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-an-entity-in-yaml

W przypadku dodania też `state_class` dla encji będą też liczone statystyki czyli np. przyrosty dzienne/godzinowe.

**Comment by Melgan** [comment]
> Samodzielnie można sobie dodać `device_class` przez "customizecje" https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-an-entity-in-yaml
> 
> W przypadku dodania też `state_class` dla encji będą też liczone statystyki czyli np. przyrosty dzienne/godzinowe.

jesteś w stanie podesłać swój configuration.yaml (oczywiście tylko fragment dotyczący energa)? Jak masz gotowe i przetestowane na pewno będzie to najlepsze

**Comment by paki111** [comment]
Np. tak:
```yaml
  - platform: rest
    resource: http://localhost:8000/13100490/A%2B/1
    name: "kotłownia 24a A+ taryfa 1"
    unique_id: 13100490_apt1
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.countner.meter_value | round(2) }}"
    device_class: energy
    state_class: total_increasing
```

Generalnie to jest to co autor wskazał w dokumentacji https://github.com/tcich/ha-addon-energa-meter/tree/main/src
a dodałem tylko `device_class` i `state_class`
